spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.199.133}:3306/db_example
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
