spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:82.156.217.25}:3306/db_example
    username: springuser
    password: ThePassword#1
    driver-class-name: com.mysql.cj.jdbc.Driver
